### ISSUE TITLE
The vectorizalisad image returned by the package is composed of "dots" (first image attached). How can I have a more "uniform" result instead?

### ISSUE THREAD

**Issue by damiano216** [tomayac/esm-potrace-wasm#10]
Hello, 
I have a question on how to improve the result returned by the package, and thought someone here may help.

The result returned by the package is composed of a lot of small dots, here is the attachment:
![dots](https://user-images.githubusercontent.com/58330717/196143477-522b5c4d-351d-4dc6-b6ee-fcb81f7a458d.png)

However, I would link to obtain a more "uniform" result, link this other attachement:
![nodots](https://user-images.githubusercontent.com/58330717/196144002-1ec03bc4-a9e7-4fc2-8a1a-720999957087.png)

Does someone know how I could achieve it?

Thanks very much

**Comment by tomayac** [comment]
Try bumping up the reduce speckles setting. If you use the package via the GUI https://svgco.de/, it's in the upper left corner. In this case, I also found the result improves a lot by adding more colors (5 color steps is the default, bumped up to 20 for better results).

![Screenshot 2022-10-17 at 11 44 43](https://user-images.githubusercontent.com/145676/196146016-0597c09f-f935-4154-b56c-8fdeafe93e2b.png)

**Comment by damiano216** [comment]
Hi Tomayac,
Thanks for your reply.

The solution you propose works well on a small portion of the image, but if I use the same settings for the complete image, the result is not as good.

Here is two screenshots for your reference.

![image](https://user-images.githubusercontent.com/58330717/196161574-037904ce-3265-459b-b182-e16ae4ac17c3.png)
![image](https://user-images.githubusercontent.com/58330717/196161697-3f12c2e0-7b43-4505-9360-36cb286be176.png)

Thanks!

**Comment by tomayac** [comment]
Can you share the whole image?

**Comment by damiano216** [comment]
![image](https://user-images.githubusercontent.com/58330717/196162856-5e9a76e5-ca6c-45d7-9389-6bee2f61b725.jpeg)
Here is the image

**Comment by tomayac** [comment]
Yeah, there's really not much the software could do due to the heavy compression artifacts and the watermarks. The source of the image seems to be https://www.istockphoto.com/vector/minimal-woman-face-gm1195384554-340700497.
