### ISSUE TITLE
NodeJS Support

### ISSUE THREAD

**Issue by meftunca** [tomayac/esm-potrace-wasm#11]

**Comment by tomayac** [comment]
There are already many excellent potrace ports for Node.js: https://www.npmjs.com/search?q=keywords:potrace. The present package is specifically aimed at running potrace in the browser.

**Comment by meftunca** [comment]
So does it support color output?

**Comment by tomayac** [comment]
Not directly, but see the [FAQ](https://potrace.sourceforge.net/faq.html#features).
