### ISSUE TITLE
Possible to remove `document.body.append(canvas)`?

### ISSUE THREAD

**Issue by kenfehling** [tomayac/esm-potrace-wasm#9]
Hi, thanks for this fork! I was wondering if it would be possible to remove the call to `document.body.append(canvas)` on [Line 86](https://github.com/tomayac/esm-potrace-wasm/blob/main/src/potrace.js#L86) so it doesn't automatically add a canvas node to the page? Or would that break something?

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/esm-potrace-wasm/commit/694f4f6371a7207dccc71b638ba866afe031a799. I have just released `v0.4.1` that includes this fix. Thanks for the suggestion, I think this was a leftover from a debugging session.
